---
- name: Ensure DB home is empty on all nodes
  shell: "rm -rf {{ db_home }}/* {{ db_home }}/.patch_storage /tmp/OraInstall*"

- name: Unzip DB home on primary node only
  unarchive:
    src: "{{ stage_dir }}/{{ db_zip }}"
    dest: "{{ db_home }}"
    remote_src: true
    owner: oracle
    group: oinstall
  when: inventory_hostname in groups['rac_primary']

- name: Run DB software install from primary node
  become_user: oracle
  shell: |
    cd {{ db_home }}
    ./runInstaller -silent -ignorePrereqFailure -waitforcompletion \
      oracle.install.option=INSTALL_DB_SWONLY \
      UNIX_GROUP_NAME=oinstall \
      INVENTORY_LOCATION={{ ora_inventory }} \
      ORACLE_HOME={{ db_home }} \
      ORACLE_BASE={{ oracle_base }} \
      oracle.install.db.InstallEdition=EE \
      oracle.install.db.OSDBA_GROUP=dba \
      oracle.install.db.OSOPER_GROUP=oper \
      oracle.install.db.OSBACKUPDBA_GROUP=backupdba \
      oracle.install.db.OSDGDBA_GROUP=dgdba \
      oracle.install.db.OSKMDBA_GROUP=kmdba \
      oracle.install.db.OSRACDBA_GROUP=racdba \
      oracle.install.db.CLUSTER_NODES=mzr1.lab.maz,mzr2.lab.maz
  when: inventory_hostname in groups['rac_primary']
  register: db_install
  failed_when:
    - db_install.rc not in [0, 6]
    - "'Successfully Setup Software' not in db_install.stdout"

- name: Fix wrong hardcoded DB home path if present
  shell: |
    for f in \
      {{ db_home }}/root.sh \
      {{ db_home }}/install/orabasetab \
      {{ db_home }}/install/utl/rootmacro.sh \
      {{ db_home }}/install/root_schagent.sh \
      {{ db_home }}/network/install/sqlnet/setowner.sh \
      {{ db_home }}/rdbms/install/rootadd_filemap.sh
    do
      [ -f "$f" ] && sed -i "s|/u01/app/oracle/product/23.0.0/dbhome_1|{{ db_home }}|g" "$f"
    done
  changed_when: false

- name: Run DB root.sh on all RAC nodes
  shell: "{{ db_home }}/root.sh"
  register: dbroot
  failed_when: dbroot.rc != 0
  changed_when: true
  when: hostvars[groups['rac_primary'][0]].db_install is succeeded

- name: Validate DB home binaries
  shell: |
    {{ db_home }}/bin/sqlplus -v
    test -s {{ db_home }}/bin/oracle
    ls -lh {{ db_home }}/bin/oracle
  changed_when: false
