[rac_primary]
zoom1 ansible_host=192.168.56.70 public_ip=192.168.56.70 private_ip=192.168.57.70 vip_ip=192.168.56.72 node_fqdn=zoom1.lab.maz

[rac_secondary]
zoom2 ansible_host=192.168.56.71 public_ip=192.168.56.71 private_ip=192.168.57.71 vip_ip=192.168.56.73 node_fqdn=zoom2.lab.maz

[rac_nodes:children]
rac_primary
rac_secondary

[rac_nodes:vars]
ansible_user=root
ansible_connection=ssh
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
